[package]
name = "maiden-run"
version = "0.1.0"
authors = ["Greg Wuller <greg@afofo.com>"]
edition = "2018"

[dependencies]
clap = "2.33.1"
http = "0.2.1"
notify = "4.0.15"
url = "2.1.1"
tungstenite = "0.11.0"
